### ISSUE TITLE
How to understand the "s-*" metrics used in hypergraph anlysis?

### ISSUE THREAD

**Issue by mgao97** [pnnl/HyperNetX#109]

**Comment by brendapraggastis** [comment]
Hypergraphs are generalizations of graphs. For many graph metrics distance is defined in terms of the length of the shortest path between nodes. But in hypergraphs paths have both length and width, which we reference with the parameter _s_. This affords the ability to define an _s_-distance. We describe this in [Tutorial 7](https://github.com/pnnl/HyperNetX/blob/master/tutorials/Tutorial%207%20-%20s-centrality.ipynb) in the library. 
With large datasets _s_-connectedness can serve as measure of strength of bond between hyperedges. For a detailed study of s-metrics, please see our paper: 
[Aksoy, S.G., Joslyn, C., Ortiz Marrero, C. et al. Hypernetwork science via high-order hypergraph walks. EPJ Data Sci. 9, 16 (2020).](https://doi.org/10.1140/epjds/s13688-020-00231-0)

**Comment by mgao97** [comment]
Thank you! 

What are the differences between the s-* metrics in s-linegraph and metrics in hypergraphs?
