### ISSUE TITLE
create the directed hypergraph weighted

### ISSUE THREAD

**Issue by pharaon-dev** [pnnl/HyperNetX#110]
Good day sir,
how to create weighted directed hypergraph from hypernetx (code example). 

Cordially,
Ghislain

**Comment by Voltstav** [comment]
Dear, 
What is the expected release date for the new version?

Thank you,
S.

**Comment by bonicim** [comment]
@Voltstav, 2.0.0 just came out yesterday. See links below:

PyPi
https://pypi.org/project/hypernetx/

Release notes
https://github.com/pnnl/HyperNetX/releases/tag/v2.0.0
