### ISSUE TITLE
AttributeError: module 'hypernetx.algorithms.hypergraph_modularity' has no attribute 'hypergraph_modularity'

### ISSUE THREAD

**Issue by MCDalvean** [pnnl/HyperNetX#119]
Thanks for this library.

One issue I am having a the moment is the absence of 'hypergraph_modularity' as per the following error:
AttributeError: module 'hypernetx.algorithms.hypergraph_modularity' has no attribute 'hypergraph_modularity'.

The various imports have been fulfilled:
import pandas as pd
import numpy as np
import pickle
import random

import igraph as ig
import hypernetx as hnx
import hypernetx.algorithms.hypergraph_modularity as hmod
import hypernetx.algorithms.generative_models as gm

Any assistance on this would be greatly appreciated.

**Comment by bonicim** [comment]
@MCDalvean The hypergraph_modularity module does not have a 'hypergraph_modularity' attribute, but it does have a [`modularity`](https://github.com/pnnl/HyperNetX/blob/master/hypernetx/algorithms/hypergraph_modularity.py) attribute. Can you please describe how to reproduce this error?

**Comment by bonicim** [comment]
Resolved in v2.3.2.
