### ISSUE TITLE
TeX in docstrings causes DeprecationWarning.

### ISSUE THREAD

**Issue by drj11** [pnnl/HyperNetX#128]
**Describe the bug**

On Python 3.11 when i `import hypernetx` i get a few warnings:

```
>>> import hypernetx as hnx
/Users/drj/prj/HyperNetX/hypernetx/algorithms/homology_mod2.py:1: DeprecationWarning: invalid escape sequence '\{'
  """
/Users/drj/prj/HyperNetX/hypernetx/algorithms/homology_mod2.py:544: DeprecationWarning: invalid escape sequence '\m'
  """
/Users/drj/prj/HyperNetX/hypernetx/algorithms/homology_mod2.py:737: DeprecationWarning: invalid escape sequence '\{'
  """
/Users/drj/prj/HyperNetX/hypernetx/algorithms/laplacians_clustering.py:42: DeprecationWarning: invalid escape sequence '\g'
  """
```

These are causes by the TeX code appearing inside Python docstrings. Probably the simplest approach would be to make the docstrings raw by changing `"""` to `r"""` at the beginning of the affected docstrings [edit: as has been done in `s_centrality_measures.py` for example].

In addition the affected docstring in `laplacians_clustering.py` looks like it needs some dollar signs, but i am not familiar with your post-processing documentation tools.

Whilst i found this during my review for JOSS, i do not require it to be fixed for acceptance.

**Environment (please complete the following information):**
 - macOS Darwin 20.6.0
 - Python 3.11.4 (main, Jun 20 2023, 16:52:35) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin

**Comment by bonicim** [comment]
Fixed in [v2.1.3](https://github.com/pnnl/HyperNetX/releases/tag/v2.1.3).
