### ISSUE TITLE
Broken link to your paper in Connected Components section of Tutorial 1

### ISSUE THREAD

**Issue by drj11** [pnnl/HyperNetX#130]
**Describe the bug**

The hyperlink https://epjdatascience.springeropen.com/articles/10.1140/epjds/s13688-020-00231-0%22 appears in Tutorial 1 in the Connected Components section, but the link is broken (thanks Springer).

**Comment by bonicim** [comment]
Fixed in [v2.1.3](https://github.com/pnnl/HyperNetX/releases/tag/v2.1.3).
