### ISSUE TITLE
Bad math syntax in hypgraph101.html documentation

### ISSUE THREAD

**Issue by drj11** [pnnl/HyperNetX#132]
**Describe the bug**

In (the compiled documentation file) hypergraph101.html there is an occurrence of ``:math:`s`-walk`` in the section "Walks Have Length and Width". I suspect that this is a syntax typo.

**Comment by bonicim** [comment]
Fixed in [v2.1.3](https://github.com/pnnl/HyperNetX/releases/tag/v2.1.3).
