### ISSUE TITLE
[joss] Documentation contains unrendered LaTeX math

### ISSUE THREAD

**Issue by szhorvat** [pnnl/HyperNetX#139]
Some documentation pages contain `$`-delimited LaTeX notation that is not rendered.

Example:

https://hypernetx.readthedocs.io/en/latest/modularity.html

<img width="618" alt="image" src="https://github.com/pnnl/HyperNetX/assets/1212871/ac3052a3-2845-4cc7-b670-8cc2f798476b">

Ref: https://github.com/openjournals/joss-reviews/issues/6016

**Comment by bonicim** [comment]
Fixed in [v2.3.2](https://github.com/pnnl/HyperNetX/releases/tag/v2.3.2)
