### ISSUE TITLE
[joss] More clarity on (optional) dependencies

### ISSUE THREAD

**Issue by szhorvat** [pnnl/HyperNetX#142]
I followed the installation instructions in https://hypernetx.readthedocs.io/en/latest/install.html and installed into a new virtual environment from PyPI using `pip install hypernetx`. When I load the package, the following message is shown:

```
>>> import hypernetx
 No module named 'igraph'. If you need to use hypernetx.algorithms.hypergraph_modularity, please install additional packages by running the following command: pip install .['all']
```

This is not an ideal user experience, and is likely confusing to some new users. They may be wondering: "Did I install correctly? Will some essential functionality not be working?"

I suggest:

 - Include more information in the documentation about what dependencies are requires for significant submodules
 - Since most people install from PyPI, include instructions on how install all optional dependencies with a single command
 - The warning message on package load gives instructions which only work when installing from sources. This is not user friendly. Most people would install from PyPI
 - Would it make sense to issue this warning only when people actually try to use `hypernetx.algorithms.hypergraph_modularity` instead of on package load? This is a more common practice.

Ref: https://github.com/openjournals/joss-reviews/issues/6016

**Comment by bonicim** [comment]
Resolved in release 2.14

**Comment by szhorvat** [comment]
Is `pip install hypenetx['all']` something that should be suggested?

**Comment by bonicim** [comment]
`pip install hypenetx['all']` installs Jupyter, allowing the user to open one of the tutorials in the repo; it also installs the dependencies needed for the contagion and modularity sub-modules. The [documentation](https://hypernetx.readthedocs.io/en/latest/install.html#installing-from-source) recommends this.

**Comment by szhorvat** [comment]
Could you please clarify where the documentation mentions this command? I can only see `pip install -e .['all']` in the section about installing from source.

My impression was that the target audience of this library is not just developers, but mainly researchers. I expect most of them won't want to install from source and won't necessarily notice that `pip install hypenetx['all']` is also a valid command.

**Comment by bonicim** [comment]
I see your point about the target audience being researchers. I will update the installing from PyPi instructions  to include a snippet about `pip install hypernetx['all']`

**Comment by bonicim** [comment]
Have just updated installation steps on the docs: https://hypernetx.readthedocs.io/en/latest/install.html#id1
