### ISSUE TITLE
can hnx ignore s when computing indicators? I want to know the indicators with all sizes of edges, but not with s=1 or s=2. 

### ISSUE THREAD

**Issue by YuhuYang** [pnnl/HyperNetX#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brendapraggastis** [comment]
@YuhuYang Please clarify your question with a code snippet of what is misbehaving for you.
