### ISSUE TITLE
Wrongly placed nodes when ids overlap

### ISSUE THREAD

**Issue by ju-gem** [pnnl/HyperNetX#149]
**Describe the bug**
When drawing a hypergraph where the node and edge IDs come from the same set, the nodes with an edge ID are placed inside the edge with that ID.

**To Reproduce**
When drawing the following graph, the node 0, for example, is drawn inside edge 0 even though it is not in the edge.
```
# bipartite edge list: 
# node edge
0 1
1 1
1 3
1 4
2 2
3 4
4 0
5 0
6 2
6 4
7 3
8 3
9 3
9 4
10 3
11 0
12 3
13 2
14 0
14 4
15 3
16 2
```
```python
import pandas as pd
import hypernetx as hnx

df = pd.read_csv("hypergraphs/out.test", sep='\s+', names=("node", "edge"))
hg = hnx.Hypergraph(df, edge_col="edge", node_col="node")
hnx.draw(hg, node_radius=.5)
```
![Wrong drawing](https://github.com/pnnl/HyperNetX/assets/77753311/28d4e2d9-6fc9-4bd1-966a-ecc8b160c2de)

**Expected behavior**
The nodes shouldn't be drawn inside edges they aren't contained in. When renaming the edges (prepending 'e'), this works as expected, see image below.

![with prefix](https://github.com/pnnl/HyperNetX/assets/77753311/b2ce1ab5-551b-4971-9310-c638d8f0e82d)

**Environment (please complete the following information):**
 - OS: Windows (WSL Ubuntu)
 - Python Version: 3.10.12

**Additional context**
I believe this has to do with first generating a bipartite graph.

**Comment by brendapraggastis** [comment]
@ju-gem  I believe the new constructor has fixed this error. When I run your code I get:
![image](https://github.com/pnnl/HyperNetX/assets/39808911/40668709-e109-4fb4-a951-ee1e867c0da8)

**Comment by brendapraggastis** [comment]
@ju-gem This is an artifact of the way the draw() function is written. Positions are keyed by node and edge id, so if they are the same the node will be located at a point in the edge corresponding to an edge locator point with the same edgeid. I will submit this to our vis team to be corrected. Thanks for bringing it to our attention.
