### ISSUE TITLE
Please support nesting and directed hyperedges

### ISSUE THREAD

**Issue by dtchang** [pnnl/HyperNetX#156]
Please support nesting and directed hyperedges. They significantly enhance the power and usefulness of hypergraph. A unified and uniform definition for them is proposed in [https://arxiv.org/abs/2405.12235](url). 

For example, which is discussed in the reference, the high-order interactions among characters in the novel Les Miserables can be fully represented by a single multilevel hypergraph that uses simple, nesting and directed hyperedges, which reflects the structure and granularity, as well as their ordering, of the novel. As such, the representation is simpler, complete and more powerful.

Thanks.

**Comment by brendapraggastis** [comment]
@dtchang The HNX library can produce compound like hypergraphs. The hierarchical lattice would be an interesting addon if you would like to contribute a module for this. 
![Uploading Compounds.png…]()
