### ISSUE TITLE
Not drawing the hypergraph

### ISSUE THREAD

**Issue by ChrisGeorgakidis** [pnnl/HyperNetX#33]
I tried the programs in the tutorial and also the code of the guy that reported the other issue and i get the following error:

/usr/local/lib/python3.7/site-packages/hypernetx/drawing/rubber_band.py:97: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

I don't know if the problem is that I use python3

**Comment by brendapraggastis** [comment]
This is a warning that we will address in a future release. Is the warning preventing you from running the tutorial?

**Comment by ChrisGeorgakidis** [comment]
Exactly. I get this warning and after that the plot is not shown

**Comment by brendapraggastis** [comment]
What version of numpy are you using?

**Comment by brendapraggastis** [comment]
We will push an update shortly that should fix this.

**Comment by brendapraggastis** [comment]
An update to the drawing library has been pushed. The issue you reported should not have prevented the hypergraph from showing. Try pulling and let us know what happens.

**Comment by ChrisGeorgakidis** [comment]
ok. i will check out the new version

**Comment by ChrisGeorgakidis** [comment]
I used anaconda and worked. Maybe something is going wrong with my packages. I have also another question. Is it able to give custom labels to the edges or the nodes?

**Comment by brendapraggastis** [comment]
Hi @ChrisGeorgakidis ,
At present the displayed label is the uid of the Entity (Node or Edge) being displayed. Being able to change that might be a good feature. I will add that to our list of TODOs.
Thanks

**Comment by ChrisGeorgakidis** [comment]
I have modified the python package in order to do that. If you want I can send you the function in order to integrate it into the master. If it is possible to add custom labels to the nodes, it would be great

**Comment by brendapraggastis** [comment]
You should be able to make a pull request to the develop branch on pnnl/HyperNetX. I will review it with our developers and if it doesn't break anything we will see about integrating it into our code. Thanks!
