### ISSUE TITLE
Support for weighted Hyperedges (Jan 2022)

### ISSUE THREAD

**Issue by Vivdaddy** [pnnl/HyperNetX#82]
Hi, 
I understand that support for Weighted Hyperedges was asked in [this](https://github.com/pnnl/HyperNetX/issues/35) issue.

However, the [last question](https://github.com/pnnl/HyperNetX/issues/35#issuecomment-874583001), was not answered. Could someone please answer it?

Additionally, has there been any update regarding the weighted hyperedges now that it is early 2022?

**Comment by madelynshapiro** [comment]
Thank you for raising the issue; closing, as it's been addressed in https://github.com/pnnl/HyperNetX/issues/35#issuecomment-1005932283 .

**Update as of Aug 2022**: We are currently working on our next major release, which should significantly improve functionality for weights and other properties. We welcome any additional feedback on specific issues or improvements relating to this issue - please follow up with the details and we will do our best to address those concerns in the next release!
